### ISSUE TITLE
Use Capabilities

### ISSUE THREAD

**Issue by Boehmi-TB** [industrial-edge/Protect-Sensitive-Data#5]
Remove privilege mode

```yaml
cap_drop:
      - ALL
cap_add:
#    - only_required 
security_opt:
     - 'systempaths:unconfined'
```
